### ISSUE TITLE
Feature Request: Random option

### ISSUE THREAD

**Issue by UnicronBE** [dkanada/jellyfin-plugin-intros#10]
Hey, love the plugin, really adds something to the experience :) As I'm terrible at making my mind up, it would be nice to have a random option (possibly with a blocklist option).

Thanks!

**Comment by TraumaGuy** [comment]
> Hey, love the plugin, really adds something to the experience :) As I'm terrible at making my mind up, it would be nice to have a random option (possibly with a blocklist option).
> 
> Thanks!

More than a blocklist,it would be great to be able to whitelist specific videos and randomize the played one.

Even better if you could configure specific whitelist for specific libraries.

**Comment by grravity** [comment]
I agree with whitelisting, select a number few, and have it randomize the played roll.
This could also be worked in hand with #11 to randomize more towards genres if one wishes.

**Comment by dkanada** [comment]
Basic support for random intros should exist in the latest update, can anyone confirm?

**Comment by TraumaGuy** [comment]
> 
> 
> Basic support for random intros should exist in the latest update, can anyone confirm?

Can confirm. It works! thanks for this update.

It is possible to add some kind of basic "whitelisting" to choose which ones will be played? Even if it's not at GUI level, something like a text listing that the plugins reads to choose from would be enough for now. There are some nice prerolls in the list, but also some extremely long that I'm sure most people would want to avoid.

**Comment by Weedalf** [comment]
#23 I improved the ramdom function and added a textfield to add own pre rolls from vimeo

**Comment by dkanada** [comment]
Can anyone here confirm that the plugin settings can be changed in the 1.2.1 version? It seems there are some reports about the settings not saving.
