### ISSUE TITLE
Hide playback bar during intro

### ISSUE THREAD

**Issue by mholt** [dkanada/jellyfin-plugin-intros#14]
This is a really fun plugin! I notice that the playback bar (the scrub bar, and controls) appears during the intro/preroll videos; especially while Chromecasting, this is distracting.

Is it possible for plugins to hide the playback bar? If so, it'd be great if this plugin could hide the playback bar by default when the intro is playing. (It should still be accessible by interacting with the screen.)

**Comment by dkanada** [comment]
Unfortunately that's not something I can do from a plugin, it would be handled on a per-client basis.

**Comment by dkanada** [comment]
It might be possible from the web client though, which I believe is the only client that supports intros at the moment.

**Comment by mholt** [comment]
Bummer; alright, I'll open an issue there. Thanks!
