### ISSUE TITLE
Unable to configure

### ISSUE THREAD

**Issue by 004a** [dkanada/jellyfin-plugin-intros#22]
I have installed the plugin successfully yet I am unable to configure it.

I see this issue with 1.1.0.0 - 1.2.1.0. I have not tried prior versions.

The plug-in does work but always shows Neon Blue, which I have never attempted to set.

When opening the plug-in for configuration, it always defaults to 80s Lambo and 240p. Selecting another preroll and resolution, then save, causes the server to soft reload (as expected) but the configuration is not saved.

I am running 10.6.4 in a docker container from the linuxserver/jellyfin:latest image.

**Comment by dkanada** [comment]
What browser version are you using? Have you tried wiping the browser cache? I'm relatively certain the latest update has solved the issue on modern browsers, but if you have a cache of the old plugin assets it could be causing issues.

**Comment by 004a** [comment]
I've tried multiple browsers on multiple OS's, all result in the same behaviour:

The Jellyfin embedded browser on the iOS app, iOS Safari, macOS Opera, macOS Firefox, and macOS Safari.

**Comment by 004a** [comment]
Is there a method or configuration file to manually configure the plugin?

**Comment by 004a** [comment]
Is there a method or configuration file to manually configure the plugin?

**Comment by dkanada** [comment]
Can you uninstall and then reinstall the plugin and see if that helps? You can also manually configure it from the same location your Jellyfin configuration should be, although I'm not exactly sure where that is either.

**Comment by 004a** [comment]
I haven't yet tried to uninstall/reinstall. Though I did find what looks to be the config XML in `config/data/plugins/configurations/Jellyfin.Plugin.Intros.xml`

```xml
<?xml version="1.0"?>
<PluginConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Intro>443404335</Intro>
  <Resolution>1080</Resolution>
  <Id>58df87cb-eeb4-42de-a7fc-6a86502979d5</Id>
</PluginConfiguration>
```

Does this look valid to you? I looked around the prerolls site to attempt to see if the Intro or ID looked similar to one of the prerolls and didn't seem to find a correlation.

**Comment by 004a** [comment]
I also did find the location of the currently downloaded video: `config/cache/intros/443404335-1080.mp4`

Which matches and references the Intro tag in the XML above.

**Comment by dkanada** [comment]
If you change the resolution in the config to 720 and it downloads a new video, it's probably working.

**Comment by 004a** [comment]
I have tried many different testing iterations, none have proven any success:

1. Initially tried simply changing the resolution in the XML file. No new intro was downloaded.
2. Tried changing the video identifier to another one in your list.
3. Moved the intro video it did download at one point.
4. Moved the configuration file.
5. Deleted the plugin, and reinstalled same version.
6. Deleted the plugin, and attempted to install a prior version [though it kept force downloading the latest, even with the plugin updater scheduled task disabled].
7. Completely blew away the plugin, and all referenced dirs for the plugin, and reinstalled.

Unfortunately none of these iterations have resulted in writing a configuration XML file, nor downloading any intro. [Outside of the one original that was downloaded, which I think was on v1.0.1 though never could change it.]

Any thoughts?

**Comment by LeVraiRoiDHyrule** [comment]
Hi, I'm having the exact same issue. It only plays Neon Blue, not matter what I try. I have a folder with all my intros, with the correct permissions and the correct addon set up. But the addon only plays Neon Blue and doesn't play what's in the folder.

**Comment by dkanada** [comment]
@LeVraiRoiDHyrule have you tried a single local file instead of the folder? I never actually tested the folder but individual files should be working.

**Comment by dkanada** [comment]
closing in favor of #17

**Comment by rayures** [comment]
hi, 
i also have this issue. 

Jellyfin master (2021-01-18)
plugin v1.3.0.0

When opening the settings page in Jellyfin i cannot set an option or save.

it does play Neon Blue.

**Comment by PimvanderLoos** [comment]
I'm replying to this issue instead of 17 as this more accurately represents the issue I ran into (always playing Neon Blue regardless of the settings, always showing 80's Lambo on 240p).
I am currently running Jellyfin (master 2021-01-20) and Intros v1.3.0.0.

When trying to access the configuration page, I got `GET http://192.168.2.2:8097/Plugins/9482dc3b-48aa-4d3b-8224-9128d1e8e0cd/Configuration 404 (Not Found)` in the console.

After looking around a bit, I noticed that the guide in `/config/data/plugins/Intros_1.3.0.0/meta.json`  was `7cd8a933-dc8d-aa42-96cd-00a31714b8b7`, while it is `9482dc3b-48aa-4d3b-8224-9128d1e8e0cd` [right here](https://github.com/dkanada/jellyfin-plugin-intros/blob/260bf317e5a2790fa6ccfc3a9a9bd6eaf700a6a6/Jellyfin.Plugin.Intros/Plugin.cs#L16). 
After I changed the guid in this file and restarting Jellyfin, the configuration page actually displayed the Neon Blue @ 1080p file it had been playing and any changes I made were applied properly.

After reinstalling the plugin from your repository, the guid reverted to the old one and I was unable to change the intro again.

**Comment by rayures** [comment]
> 
> 
> I'm replying to this issue instead of 17 as this more accurately represents the issue I ran into (always playing Neon Blue regardless of the settings, always showing 80's Lambo on 240p).
> I am currently running Jellyfin (master 2021-01-20) and Intros v1.3.0.0.
> 
> When trying to access the configuration page, I got `GET http://192.168.2.2:8097/Plugins/9482dc3b-48aa-4d3b-8224-9128d1e8e0cd/Configuration 404 (Not Found)` in the console.
> 
> After looking around a bit, I noticed that the guide in `/config/data/plugins/Intros_1.3.0.0/meta.json` was `7cd8a933-dc8d-aa42-96cd-00a31714b8b7`, while it is `9482dc3b-48aa-4d3b-8224-9128d1e8e0cd` [right here](https://github.com/dkanada/jellyfin-plugin-intros/blob/260bf317e5a2790fa6ccfc3a9a9bd6eaf700a6a6/Jellyfin.Plugin.Intros/Plugin.cs#L16).
> After I changed the guid in this file and restarting Jellyfin, the configuration page actually displayed the Neon Blue @ 1080p file it had been playing and any changes I made were applied properly.
> 
> After reinstalling the plugin from your repository, the guid reverted to the old one and I was unable to change the intro again.

checked for this in my setup. 

In de console  i see '500 internal server error' when pressing 'save'. 
checked the meta.json, but this has the right GUID.
