### ISSUE TITLE
the trailer selection can't start !?

### ISSUE THREAD

**Issue by CustomerJFK** [dkanada/jellyfin-plugin-intros#24]
The only massage i received is:. 

Nichts hier.

Installiere den Filmvorschau-Kanal um die Film-Bibliothek mit Filmvorschauen aus dem Internet zu erweitern.

What's wrong?

**Comment by Artiume** [comment]
jellyfin-web/src/strings/de.json:759:    "MessageNothingHere": "Nichts hier.",

jellyfin-web/src/strings/de.json:758:    "MessageNoTrailersFound": "Installiere den Filmvorschau-Kanal um die Film-Bibliothek mit Filmvorschauen aus dem Internet zu erweitern.",

**Comment by dkanada** [comment]
Not sure, I'd need a bit more information to figure out the issue.
