### ISSUE TITLE
Help with PLUGIN INTROS with own pre-videos!

### ISSUE THREAD

**Issue by EduardoLSN** [dkanada/jellyfin-plugin-intros#26]
Hi, I'm from Brazil, forgive my English, I'm not good with words. I've been using Jellyfin these past few days! I tried to use your VIDEO INTRODUCTION PLUGIN, but I couldn't, I have my own MP4 videos with 1080p resolution, I tested all versions of your PLUGIN, the videos are saved in a folder on the same PC as jellyfin installed. I wanted a help to be able to run the pre-videos I have using your plugin! Thank you and congratulations!

**Comment by dkanada** [comment]
I haven't tested it with a folder yet, there might be issues. Does a single file work instead?

**Comment by EduardoLSN** [comment]
Yes, with only one file works!  
Example:

Local Source 
C:\EmbyMEDIA\Videos\Stamp_7_FullHD.mp4
Add a file or directory to use files instead of remote videos. Items in a directory will be randomized.

Now when you put only the folder, it does not work!

**Comment by doodlebro** [comment]
I can confirm single files work, but directories are broken. Windows 10 here if that matters.

**Comment by Vitz1988** [comment]
Hi, is there a chance this plugin could be updated to get directories to work? I love Jellyfin but I really miss having this functionality from when I was using Emby.

Thank you for your work!

**Comment by Gotrees** [comment]
This would be a great feature!
