### ISSUE TITLE
Prerolls.video telling users custom video in Jellyfin needs workaround

### ISSUE THREAD

**Issue by raoulfasel-da** [dkanada/jellyfin-plugin-intros#27]
Hi,

This page tells users that a custom video needs a workaround.
https://prerolls.video/how-to-add-prerolls/

![Screenshot from 2021-01-26 10-24-10](https://user-images.githubusercontent.com/75372152/105826348-f09b4800-5fc0-11eb-803a-c9fc2fd0ee23.png)

I actually added a local custom video using the settings page.

Can we notify the owner of the website? Is there actually documentation about this feature?

I would like to help!

**Comment by dkanada** [comment]
cc @owenashurst

**Comment by preroller** [comment]
this is fixed. sorry it took me so long to remove it!
