### ISSUE TITLE
Intro not launch on Android TV app for TV show library

### ISSUE THREAD

**Issue by jordanpantin** [dkanada/jellyfin-plugin-intros#30]
Hi,

I think I have a issue on Android TV app. 

For a video of TV show library, the intro does not start. 

But it's ok for a video of a movie library.

Version jellyfin server : 10.6.4
Version Android APP : 0.11.5

PS : Thanks so much for this plugin !

**Comment by dkanada** [comment]
This would be an issue with the Android TV client, so I'd suggest you open an issue in that repository. My plugin can provide intros but the clients have to request and play them for it to work.
