### ISSUE TITLE
Cannot get the repository to work

### ISSUE THREAD

**Issue by TECHNETWORKINGSOLUTIONS** [dkanada/jellyfin-plugin-intros#31]
Everytime I put https://dkanada.xyz/plugins/manifest.json
It just doesn’t work and when I check my Jellyfin console it say error and failed to deserialize plugin and suggestions 
Would be cool if I could get this up and running

**Comment by Brickme** [comment]
Version: 10.7.5 Not showing.

**Comment by dkanada** [comment]
Is it working for either of you now? I just fixed a small problem.

**Comment by Brickme** [comment]
> Is it working for either of you now? I just fixed a small problem.

Yes, thank you. 
![FireShot Capture 003 - Plugins - jellyfin](https://user-images.githubusercontent.com/43787229/118365359-6fb18d80-b56a-11eb-91b8-64e6d6ac436a.png)

**Comment by TECHNETWORKINGSOLUTIONS** [comment]
Ayyyo Still having a problem

**Comment by TECHNETWORKINGSOLUTIONS** [comment]
![Uploading 32313D18-999D-4C9F-A09D-723740B5060D.png…]()
