### ISSUE TITLE
Not compatible with jellyfin 10.7.5

### ISSUE THREAD

**Issue by gonzalezb** [dkanada/jellyfin-plugin-intros#33]
The current version does not work with jellyfin 10.7.5 I tried I just get installing error.

**Comment by dkanada** [comment]
Is it working now? I just added a new certificate, maybe that was the issue.

**Comment by Brickme** [comment]
> The current version does not work with jellyfin 10.7.5 I tried I just get installing error.

![FireShot Capture 006 - Plugins - jellyfin](https://user-images.githubusercontent.com/43787229/118365561-45ac9b00-b56b-11eb-8c1f-d386025c5c2b.png)

Confirmed Version: 10.7.5 Working on Operating System: Linux, - Architecture: Arm64

**Comment by gonzalezb** [comment]
I made my own personal repo and got it working the logs shows the cert was the issue works now thank you. I was a idiot haha trying to figure out what was going on with it haha.w
