### ISSUE TITLE
STILL HAVING ISSUES WITH REPOSITORY 

### ISSUE THREAD

**Issue by TECHNETWORKINGSOLUTIONS** [dkanada/jellyfin-plugin-intros#34]
Everytime I put https://dkanada.xyz/plugins/manifest.json
It just doesn’t work and here’s my console It’ll say what’s going wrong.

![A1FA6C9D-DD25-4AB5-882D-D5187D284B02](https://user-images.githubusercontent.com/82411304/118371228-9aefa900-b579-11eb-95e2-d7aba3defe78.png)

**Comment by TraumaGuy** [comment]
There was a problem with SSL certificates, but it seems to be working now

**Comment by dkanada** [comment]
@TECHNETWORKINGSOLUTIONS are you sure there is still an issue?

**Comment by TECHNETWORKINGSOLUTIONS** [comment]
@dkanada Yes it appears to be giving me the same message.
Do you know if it could be my firewall or router refusing to connect 
or something on your end blocking my server?
when I enter the URL repo on just like a normal browser i can get to it no problem

**Comment by dkanada** [comment]
Are you sure you're not seeing older logs? I would try removing the plugin completely and restarting the server, just to be safe.

**Comment by TECHNETWORKINGSOLUTIONS** [comment]
Yes, and I’ve just done what you said and still get the same results unfortunately.
