### ISSUE TITLE
android tv crash

### ISSUE THREAD

**Issue by cyberbabacool** [dkanada/jellyfin-plugin-intros#43]
Hello, first thanks for this plugin :)
I have an issue when I try to play a video on google tv jellyfin app, if the plugin is enabled jellyfin crash but it is working if I launch a video on my computer web brower. I had to disable it for now until I find a fix.

**Comment by oddstr13** [comment]
This issue likely belongs to https://github.com/jellyfin/jellyfin-androidtv as it is a playback problem

**Comment by mooninite** [comment]
FYI - Opened: https://github.com/jellyfin/jellyfin-androidtv/issues/2163
