### ISSUE TITLE
Stuck on same pre-roll

### ISSUE THREAD

**Issue by gllyrjones** [dkanada/jellyfin-plugin-intros#6]
Thanks for the plugin - brilliant!
One issue for me!
I'm running docker jellyfin on Ubuntu 18.

My pre roll is stuck on the same one!

It will only change if I select a pre-roll that I haven't used before.
As I have gone through them all I'm now unable to change to others.
I have cleared all the cache in the jellyfin scheduler.

Any ideas?

I suspect its some sort of cache issue.
Thanks

**Comment by dkanada** [comment]
I have a few ideas for this one so I'll try and get a fix out sometime this week. For now you can probably fix it by deleting the plugin configuration and the `intros` folder in the metadata directory.

**Comment by gllyrjones** [comment]
I couldn't find the intro folder in the metadata. My workaround was to delete the container and run again. Thanks

**Comment by dkanada** [comment]
This should be resolved in the latest version, can you give it a try? The plugin will still show up as 1.0.0 since I forgot to bump the version but the catalog should show 1.0.1 as an option.
