### ISSUE TITLE
Feature request: Custom pre roll video

### ISSUE THREAD

**Issue by mdic** [dkanada/jellyfin-plugin-intros#7]
First of all, many thanks for this plugin.
I was trying to customize it by replacing the downloaded video (from prerolls) with a custom one I have, but everytime the custom file gets replaced with the "correct" one from prerolls. Would it be possible to have, among the video options, one where a user can select an already available video from the library to be used as intro to all the movies?
Thanks in advance.

**Comment by ssamjh** [comment]
+1 for this

**Comment by JefCarlier** [comment]
+1 i have uploaded my custom pre-roll to https://prerolls.video in the jellyfin category and has been approved but it does not seem to detect it.

**Comment by JefCarlier** [comment]
For the people reading this i found a simple workaround. 

1. Upload your video to vimeo. 
2. Copy your video ID.
3. Go to plugin settings and open your browser debugger (f12 on firefox)
4. Select one of the dropdown items and replace the value="" with your vimeo ID

**Comment by grravity** [comment]
Good workaround, however it would be nice to be able to avoid vimeo if we please. For example if we wanted to use Peertube, or just host with custom files.

**Comment by EduardoLSN** [comment]
Tenho uma pasta com pré vídeos... Mas não roda... No Emby roda perfeitamente...

**Comment by dkanada** [comment]
This has been added in the latest version.

**Comment by mdic** [comment]
Thanks a lot, works perfectly!
