### ISSUE TITLE
Any reason this isn't apart of the main plugin repostiories?

### ISSUE THREAD

**Issue by Darkwolf1515** [dkanada/jellyfin-plugin-intros#8]
Just wondering since you're listed as a part of the core team, and pre rolls is a native feature. Not a bad thing per say, I'm just confused as to why its not.

But Its great nonetheless, thanks for all the work you do!

**Comment by dkanada** [comment]
I scrape these videos without using the official API from Vimeo, and thus can't put this plugin in the official repository.

**Comment by Darkwolf1515** [comment]
> 
> 
> I scrape these videos without using the official API from Vimeo, and thus can't put this plugin in the official repository.

Gotcha, that makes sense.

So I have to ask, is this plugin meant to be the only way to have prerolls in jellyfin (since youre a core member I thought you'd know) or is there still plans for its native integration without the plugin, and if so, will they work in tandem, or just be their own things.

Thanks!

**Comment by dkanada** [comment]
I hope more intro providers will show up over time, including within the official repository.

**Comment by Extarys** [comment]
Suggestion: You could supply this plugin without videos and the end user would have to download the intros they want. Your plugin would be the official plugin repo then. You can also have this one here for those who prefer web scrapping.
