### ISSUE TITLE
"Alamo Drafthouse" is not universal.

### ISSUE THREAD

**Issue by Darkwolf1515** [dkanada/jellyfin-plugin-intros#9]
Ends with a giant plex logo, should be replaced with jellyfin or just have all logos removed.

**Comment by dkanada** [comment]
I wasn't aware of that. Perhaps we can find a link for the generic videos so they still exist on Jellyfin. @njchaltry you might want to move those three back into the Plex category for now, although I don't think it's mission critical.

**Comment by Darkwolf1515** [comment]
> 
> 
> I wasn't aware of that. Perhaps we can find a link for the generic videos so they still exist on Jellyfin. @njchaltry you might want to move those three back into the Plex category for now, although I don't think it's mission critical.

Neither do I, but I thought it was at least worth pointing out.

**Comment by njchaltry** [comment]
Thanks for pointing this out @Darkwolf1515 - only https://vimeo.com/440793415 ended with a Plex logo. I just replaced the video with the Plex logo removed to match the other Alama Drafthouse pre-rolls. It's probably better this way for copyright reasons.

**Comment by njchaltry** [comment]
> Perhaps we can find a link for the generic videos so they still exist on Jellyfin.

@dkanada the generic/universal videos have their own [showcase](https://vimeo.com/showcase/7387779) as well. I can easily remove them from the Jellyfin showcase if you want to pull these separately from a different link.

**Comment by dkanada** [comment]
I think they're fine together, the list isn't that long yet.

**Comment by dkanada** [comment]
@njchaltry this is super unimportant but I figured I'd satiate my curiosity. It looks like the Jellyfin icon for the Netflix preroll might be stretched horizontally, or am I just crazy? :sweat_smile:

**Comment by njchaltry** [comment]
@dkanada I think you're right, it does look a little off. I actually didn't make this one so I'll reach out to the creator to see if he can fix it. Thanks!

**Comment by njchaltry** [comment]
@dkanada the creator was nice enough to fix the scaling on the logo so I replaced the source video with the new one. Thanks for the heads up!

**Comment by dkanada** [comment]
Thanks for the update!
